### PR TITLE
add cst icon

### PR DESCRIPTION
**Pull request by liuyong5653**

### CODE REVIEW

**Comment by zhangliang00081** [comment]
0xd714E7806F036702F778429dbE2eF2266a65896d
aed6ad6d83dfab723c6665525b5b0d89

**Comment by zhangliang00081** [comment]
0xd714E7806F036702F778429dbE2eF2266a65896d
aed6ad6d83dfab723c6665525b5b0d89

**Comment by tianlangyaoyue** [comment]
0x45da77184576ea0dE0C9D77a3D55d90E46eE81cF
30c002ce6ab5d2533c731ac1eeab479f png

**Comment by tianlangyaoyue** [comment]
[add cst icon]

**Pull request merged**
